version: '3'
services:
  index-processor:
    build: .
    environment:
      DB_CONNECTION_URI: postgresql://coin_flip:postgres@db:5432/coin_flip
    depends_on:
      - db
    volumes:
      - ./config.yaml:/app/config/config.yaml
  db:
    image: postgres:15.2
    environment:
      POSTGRES_USER: coin_flip
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
